### ISSUE TITLE
[UPDATE]: Thema von Halloween zu Fasching ändern

### ISSUE THREAD

**Issue by StrableD** [Aldammar/campusTour#5]
### Feature to Update

Der Startscreen zu der Website und die Bilder und Modelle auf der AR Seite von Thema ändern

### Update Description

- Hintergrundbid auf der index.html ändern
- Bilder am Rand ändern
- Bei den Katzenmodellen die Kostüme ändern

**Comment by Aldammar** [comment]
- [x] Hintergrundbid auf der index.html ändern
- [x] Bilder am Rand ändern
- [ ] Bei den Katzenmodellen die Kostüme ändern (müssen die Kostüme noch geändert werden? @StrableD )

**Comment by StrableD** [comment]
Müssen nicht mehr geändert werden.
